try{
throw  console.error("hello");

}catch{
    console.log("ERROR");
}